Base information now with email instead of slack id
Enanodr/logger-analitics pull request #3
Opened 2017-07-14 18:31 UTC by danielaRiesgo

Removing script for calculating average length and creating the file with base information with email and adding day and length to give Erica more information.

2017-07-14 20:06 UTC, draffo-dc requested changes

2017-07-14 20:06 UTC, Enanodr commented on logger_analyzer.rb
> +      'text_length' => slack['text'].length,
this is the amount is characters in the message. Do we want that or the amount of words?

2017-07-17 13:33 UTC, danielaRiesgo commented on logger_analyzer.rb
> +      'text_length' => slack['text'].length,
That's a good question. I'll ask Erica.

2017-07-17 14:49 UTC, draffo-dc approved these changes

2017-07-17 14:56 UTC, merged